### ISSUE TITLE
Milestones for dcrtimegui redesign

### ISSUE THREAD

**Issue by thi4go** [decred/dcrtimegui#85]
# dcrtimegui redesign

This issue will be used to track the work being done on dcrtimegui's redesign. It involves implementing the new redesign specs and finishing app improvements that are pending in our issues list.

Coordination issues: [dcrdesign](https://github.com/decred/dcrdesign/issues/131) and [dcrtimegui](https://github.com/decred/dcrtimegui/issues/67)
Specs: [adobe xd](https://xd.adobe.com/spec/2af300cc-83cf-4951-5fc8-85f2e3d389e3-5cc2/grid)

### Redesign task list

- [x] Layout
  - [x] Header
  - [x] Footer
  - [x] Body
  - [x] [pi-ui](https://github.com/decred/pi-ui) components
  
- [x] Pages
  - [x] Timestamp form
  - [x] Results
  - [x] Error Handling
- [x] Modals
  - [x] Create new
  - [x] Result status

### Improvements task list 

- [x] Mobile version
  - [x] Timestamp form
  - [x] Results

- [x] Privacy improvement (#54)
- [x] No-js fallback version (#57)
- [ ] Audit dcrtime results against dcrdata (#48)

### Milestones

- [x] Milestone # 1 - 4/11
~~Layout tasks; replace UI components for ones in pi-ui lib; foundation for new design.~~

- [x] Milestone # 2 - 11/11
~~Pages and Modals tasks; correct design specs for each element; code refactor if needed; end of redesign tasks~~

- [x] Milestone # 3 - 18/11
~~Mobile version; specs weren't delivered, but we can derive a mobile design from the specs we have;~~

- [ ] Milestone # 4 - 25/11
Remaining improvements tasks (#54, #57, #48)
